#!/bin/sh
#
# start/stop portmap daemon.
#
# chkconfig: S 41 10
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin

test -f /bin/portmap || exit 0

case "$1" in
    start)
	echo "Starting portmap daemon:"
        start-stop-daemon -S -q -x /bin/portmap

	if [ -f /var/run/portmap.upgrade-state ]; then
          echo "Restoring old RPC service information..."
          sleep 1 # needs a short pause or pmap_set won't work. :(
	  pmap_set </var/run/portmap.upgrade-state
	  rm -f /var/run/portmap.upgrade-state
        fi

	;;
    stop)
        echo "Stopping portmap daemon:"
        start-stop-daemon -K -q  -x /bin/portmap
	;;
    reload)
	;;
    force-reload)
        $0 restart
	;;
    restart)
	pmap_dump >/var/run/portmap.state
        $0 stop
        $0 start
	if [ ! -f /var/run/portmap.upgrade-state ]; then
          sleep 1
	  pmap_set </var/run/portmap.state
	fi
	rm -f /var/run/portmap.state
	;;
    *)
	echo "Usage: /etc/init.d/portmap {start|stop|reload|restart}"
	exit 1
	;;
esac

exit 0

