#!/bin/sh

#BIND=127.0.0.1:8888
#BIND=unix:/dev/shm/php.socket
BIND=/var/run/php.sock
USER=root
PHP_FCGI_CHILDREN=4
PHP_FCGI_MAX_REQUESTS=1000
PHP_CGI=/bin/php-cgi
PHP_CGI_NAME=`basename $PHP_CGI`
PHP_CGI_ARGS="-b $BIND"
RETVAL=0

PATH=/sbin:/bin:/usr/sbin:/usr/bin

start() {
	echo -n "Starting PHP FastCGI: "
	start-stop-daemon -S -b -x $PHP_CGI -- $PHP_CGI_ARGS
	RETVAL=$?
	echo "$PHP_CGI_NAME."
}

stop() {
	echo -n "Stopping PHP FastCGI: "
	killall php-cgi
	RETVAL=$?
	echo "$PHP_CGI_NAME."
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	stop
	start
	;;
*)
	echo "Usage: php-fcgi {start|stop|restart}"
	exit 1
	;;
esac

exit $RETVAL
