#!/bin/sh

#echo "$0, $1"  >> /var/preinst


case "$1" in
  update)
    ;;
  install)
    [ -f /etc/init.d/ipsec ] && /etc/init.d/ipsec stop
    mount -o remount,rw /dev/mtdblock2 /
    ;;
  configure)
    ;;
  remove)
    ;;
  *)
    ;;
esac

exit 0
