#aaa
#
# Makefile for the linux kernel.
#

obj-y	+= cpe_int.o cpe_time.o debug_cpe.o cpe_setup.o gpio.o

obj-$(CONFIG_MMC_MOXACPU) += apb_dma.o
obj-$(CONFIG_ARCH_MOXACPU) += device.o
obj-$(CONFIG_PCI) += ftpci.o
