#ifndef		_IPVARS_H_
#define		_IPVARS_H_

CVoidType	ipInit (void);

#define IPFORWARDING	1
#define IPDEFAULTTTL	2
#define IPINRECEIVES	3
#define IPINHDRERRORS	4
#define IPINADDRERRORS	5
#define IPFORWDATAGRAMS 6
#define IPINUNKNOWNPROTOS 7
#define IPINDISCARDS	8
#define IPINDELIVERS	9
#define IPOUTREQUESTS	10
#define IPOUTDISCARDS	11
#define IPOUTNOROUTES	12
#define IPREASMTIMEOUT	13
#define IPREASMREQDS	14
#define IPREASMOKS	15
#define IPREASMFAILS	16
#define IPFRAGOKS	17
#define IPFRAGFAILS	18
#define IPFRAGCREATES	19
#define IPADENTADDR	20
#define IPROUTETABLE	21
#define IPNETTOMEDIA	22
#define IPROUTEDISCARD	23

#endif		/*	_IPVARS_H_	*/
