#!/bin/sh -e
# $Id: postinst,v 1.1 2000/06/19 06:09:10 herbert Exp $

if [ configure = "$1" ] && [ ! -e /etc/exports ]; then
	cat << EOF > /etc/exports
# /etc/exports: the access control list for filesystems which may be exported
#		to NFS clients.  See exports(5).
EOF
fi

#DEBHELPER#
