#!/bin/sh

#echo "$0, $1"  >> /var/postinst

case "$1" in
  update)
    ;;
  install)
    ;;
  configure)
    /home/mysql/bin/mysql_install_db --force --basedir=/home/mysql --datadir=/home/mysql/var --log-bin=Moxa-bin
    /etc/init.d/mysql.server start
    ;;
  remove)
    ;;
  *)
    ;;
esac

exit 0
