#
# Site-specific make options generated by BUILD. Please do not edit.
#

# ugidd support
UGIDD_PROG=
UGIDD_MAN=
# Location of tcp_wrapper library
LIBWRAP_DIR=-L/usr/lib
LIBWRAP_LIB=-lwrap
DEVTAB_FILE=
