/*
 * Site-specific configuration options generated by BUILD.
 * Please do not edit.
 */

/*
 * If ENABLE_DEVTAB is defined, nfsd will use the new inode
 * number generation scheme for avoiding inode number clashes
 * on big hard disks.
 */
/* #undef ENABLE_DEVTAB */

/*
 * If MULTIPLE_SERVER_READWRITE is defined, you will be able 
 * to run several nfsd process in parallel servicing all NFS 
 * requests.
 */
#define MULTIPLE_SERVERS_READWRITE

/*
 * If ENABLE_UGID_DAEMON is defined, the real rpc.ugidd is built, 
 * nfsd is built to support ugidd queries.
 * Otherwise, a dummy program is created
 */
/* #undef ENABLE_UGID_DAEMON */

/*
 * If ENABLE_UGID_NIS is defined, nfsd will support user mapping 
 * vie the client's NIS server.
 */
/* #undef ENABLE_UGID_NIS */

/*
 * if HOSTS_ACCESS is defined, ugidd uses host access control
 * provided by libwrap.a from tcp_wrappers
 */
#define HOSTS_ACCESS

/*
 * Define correct ownership of export control file
 */
#define EXPORTSOWNERUID  ((uid_t) 0)
#define EXPORTSOWNERGID  ((gid_t) 0)

/*
 * If WANT_LOG_MOUNTS is defined, every mount request will be logged
 * to syslogd with the name of source site and a path that was
 * it requested
 */
#define WANT_LOG_MOUNTS
