#!/bin/sh
LPATH=/bin
print_usage()
{
	echo "Usage: $0      ; trouble shooting for the GPRS and SIM card";
	echo ""
}
while getopts h options
do
	case $options in
	h) print_usage;
	   exit 0;;
	?) print_usage;
	   exit 2;;
	esac
done

${LPATH}/egprscmd -g
if [ $? != 0 ]; then
	exit 1 ;
else
	exit 0 ;
fi
