#!/bin/sh

#echo "$0, $1"  >> /var/postrm

case "$1" in
  update)
    ;;
  install)
    ;;
  configure)
    ;;
  remove)
    sed -ie 's/ LoadModule php5_module/# LoadModule php5_module/' /etc/apache/conf/httpd.conf
    /etc/init.d/apache start
    ;;
  *)
    ;;
esac

exit 0
