#!/bin/sh

#echo "$0, $1"  >> /var/preinst


case "$1" in
  update)
    ;;
  install)
    [ -f /etc/init.d/mysql.server ] && /etc/init.d/mysql.server stop
    ;;
  configure)
    ;;
  remove)
    ;;
  *)
    ;;
esac

exit 0
