#! /bin/bash
#
# hostapd       Start the hostapd daemon.
#
# chkconfig: 2345 20 20
#

NAME=hostapd
PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
DAEMON_OPTS="-B -P $PIDFILE /etc/hostapd/hostapd.conf"

test -f $DAEMON || exit 0

case "$1" in
  start)
    echo -ne "Starting server: $NAME"
    start-stop-daemon -S -q -x $DAEMON -- $DAEMON_OPTS ;
    echo "."
    ;;

  stop)
    echo -ne "Stopping server: $NAME"
    start-stop-daemon -K -q -p $PIDFILE
    echo "."
    ;;

  restart)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME start|stop|restart}"
    exit 1
    ;;
esac

exit 0

