# arch/arm/mach-moxaarm11/Makefile
#
# Copyright 2010 Moxa, Inc.
#
# Licensed under GPLv2

obj-$(CONFIG_MACH_MOXAMACRO)	+= setup.o irq.o time.o gpio.o system-control.o
obj-$(CONFIG_PCI)		+= pci.o
obj-$(CONFIG_PCIE)		+= pcie.o

